#!/bin/bash
if [ ! -d ~/bin ]
then
	mkdir --mode=755 ~/bin
fi
cp -p lyq ~/bin
mkdir --mode=755 ~/lunYuQuotes
cp -pu lang ~/lunYuQuotes
cp -pu LunYu-verses-pl.txt ~/lunYuQuotes
cp -pu LunYu-verses-en.txt ~/lunYuQuotes
#Checks if user home bin is in system PATH 
if [[ $PATH != ?(*:)$HOME/bin?(:*) ]]
then
	echo 'export PATH=$PATH:~/bin' >> ~/.bashrc
	source ~/.bashrc
fi
exit 0
