#!/bin/bash
if [ ! -d ~/bin ]
then
	mkdir --mode=755 ~/bin
fi
cp -p lyq ~/bin
mkdir --mode=755 ~/lyq
cp -pu lang ~/lyq
cp -pu base-pl.txt ~/lyq
cp -pu base-en.txt ~/lyq
# Checks if user home bin is in system PATH.
if [[ $PATH != ?(*:)$HOME/bin?(:*) ]]
then
	echo 'export PATH=$PATH:~/bin' >> ~/.bashrc
	source ~/.bashrc
fi
exit 0
